# benchmark config yaml
### Please fill these accordingly
data_dir: "/aux/benchmarks/bigbench/"
output_dir: "/aux/benchmarks/bigbench_out_cylon/"
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file_path: "/home/niranda/dask-local-directory/scheduler.json"
dask_profile: False
dask_dir: ./
num_workers: 1

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF1 Benchmarking Matrix
get_read_time: False
